export {Alert as ThirdAlert} from './alert/Alert'
export {Button as ThirdButton} from './button/Button'
export {Card} from './card/Card'
export {Label as ThirdLabel} from './label/Label'
export {TextHorizontalLoop} from './texts/TextHorizontalLoop'
